#!/bin/bash
read -p "Nombre de usuario a modificar: " namer
 if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 clear
 echo "Usuario $namer no existe"
 exit
 fi
clear
echo -e "\033[1;33mO que vc deseja redefinir ?\033[1;30m
1) Numero de logins
2) Fecha de expiracion
3) Mudar contraseña de usuario"
read -p "opção: " option
if [ $option -eq 1 ]; then
read -p "Qual o novo limite de logins: " liml
limite $namer $liml
exit 0
fi

if [ $option -eq 2 ]; then
echo "Qual a nova data : formato AAAA/MM/DD"
read -p ": " date
chage -E $date $namer 2> /dev/null
echo -e "\033[1;31mUsuario $namer Date: $date\033[0m"
exit
fi
if [ $option -eq 3 ]
then
read -p "Qual a nova contraseña para $namer: " contraseña
(echo "$contraseña" ; echo "$contraseña" ) |passwd $namer > /dev/null 2>/dev/null
echo "$contraseña" > /etc/VpsPackdir/contraseña/$namer
echo "Nova contraseña aplicada"
exit
fi
